DATABASE_URL = "postgresql://postgres.vfaltbploucduwmgeyga:coolSh3ep27!@aws-1-us-east-1.pooler.supabase.com:5432/postgres"
DISPATCH_PASSWORD = "dispatch123"
AR_PASSWORD = "billing123"
DRIVER_PIN = "1234"
ADMIN_PASSWORD = "admin123"
